version: '3.9'

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/php.conf:/etc/nginx/php.conf
      - ../logs/nginx:/var/log/nginx

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php
    restart: unless-stopped
    volumes:
     - ../:/app
     - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
     - ../logs/php:/var/log/php
